[general]
import = [
    "~/.config/alacritty/gruvbox_dark.toml"
]

[font]
size = 20.0

[font.normal]
family = "HackNerdFont"
style = "Regular"

[window]
opacity = 0.93

[window.padding]
x = 0
y = 0

[selection]
save_to_clipboard = true
